### ISSUE TITLE
About default options and custom options

### ISSUE THREAD

**Issue by BoBo-Git** [igortrinidad/vue-number-format#1]
First of all, it must be affirmed that this is a great library, but I think there are still some areas worthy of improvement.

I wrote the global default options in `main.js` file, when I use it as a format function, eg: `{{ vueNumberFormat(275, {}) }}`, my global default options doesn't work.

I wonder if it can support the option and default options in use to be **merged** instead of **overwriting**

`main.js`:
```javascript
import { createApp } from 'vue'
import App from './App.vue'
import VueNumberFormat from 'vue-number-format'

const app = createApp(App)

app.use(VueNumberFormat, {
    prefix: '',
    suffix: '',
    decimal: '.',
    thousand: ',',
    precision: 2,
    acceptNegative: true,
    isInteger: false
})

app.mount('#app')
```

`Some single Vue file`:
```html
<template>
{{ vueNumberFormat(275, { precision: 4 }) }}
</template>
```
I wish output `275.0000`, but output `R$275,0000`.

**Comment by igortrinidad** [comment]
Hello Bobo!

First of all thanks for the feedback and report! 

I'd just fixed the issue with defaultOptions in template usage (mixin), so please update the package to the newly version 1.2.0  `npm install vue-number-format` and you are good to go!

Have a nice day!

**Comment by BoBo-Git** [comment]
> Hello Bobo!
> 
> First of all thanks for the feedback and report!
> 
> I'd just fixed the issue with defaultOptions in template usage (mixin), so please update the package to the newly version 1.2.0 `npm install vue-number-format` and you are good to go!
> 
> Have a nice day!

That's great!

I updated the version and it has achieved the desired effect, thanks a lot!
