### ISSUE TITLE
Error when type more than 16 numbers

### ISSUE THREAD

**Issue by ngophunguyen** [igortrinidad/vue-number-format#3]
I type 11,111,111,111,111,112 {2 is wrong number},  I type 1 but it show random number in last value.

**Comment by igortrinidad** [comment]
Hello,

Working with large numbers in javascript creates some undesired side effects like making it hard to handle simple operations like divide, multiply and sum and so on, so i don't believe that this cennario is a real demand for this input library...

If you need some custom improvement or implementation, i believe it's worth to fork the project and implement the business logic that you need, you always can make a PR if it's worth the implementation and i'll be glad if do it ;)

So i'm closing this issue for now,

Thanks anyway and have a nice weekend!
