### ISSUE TITLE
Wrong number Format

### ISSUE THREAD

**Issue by mankeomorakort** [igortrinidad/vue-number-format#4]
I have an variable **amount = 3160895.00**
and I call  `vueNumberFormat(amount, {prefix: '$', decimal: '', precision: 0})`
but the result return: **$316,089,500** 

It should be **$3,160,895**

**Comment by igortrinidad** [comment]
Hello,

I added this case to the tests and it passes without error, please check if you didnt forgot something on setup or usage of the library...

![2022-03-22 11_11_30-vueNumberFormat spec js](https://user-images.githubusercontent.com/13478652/159501406-fc87789e-20c5-43ac-acb0-e33cf305891f.png)
![2022-03-22 11_11_35-functions spec js](https://user-images.githubusercontent.com/13478652/159501411-c83405cb-100c-43a6-abc2-b999a2cd8895.png)
