### ISSUE TITLE
fix folder name for git clone

### ISSUE THREAD

**Issue by maico910** [igortrinidad/vue-number-format#5]
I'm Windows user, and when I clone the repo occurred this error:

![image](https://user-images.githubusercontent.com/24510745/190881788-54db7678-64a0-4c6c-a655-a2c12c4c0b14.png)

I don't sure if this is only for Windows, but the error is caused by `:` and `(` in folder name, please remove any special character to fix this, I would like to contribute for this repo, thanks

**Comment by igortrinidad** [comment]
Thanks for finding this issue, i removed the coverage folder from the repo, i believe you can use Windows system to run the repository locally...  

And feel free to contribute bro, i was really planning to refactor this library using TS and any help is welcome!


![2022-09-18 07_50_37-create-app-version yml - vue-number-format  WSL_ Ubuntu  - Visual Studio Code](https://user-images.githubusercontent.com/13478652/190898505-0d71fa6f-f1a0-4879-9441-586b01615433.png)
