### ISSUE TITLE
Discussion: Directories structure

### ISSUE THREAD

**Issue by maico910** [igortrinidad/vue-number-format#7]
At this moment, exist two `docs` folder, `docs` and `src/docs`, imo document shouldn't be inside source folder, because is unconventional and make confusing, does exist any reason to create both folder?

**Comment by igortrinidad** [comment]
The root `docs `it's the output generated by the `src/docs` folder (a simple Vue installation to provide a live demo)... 

The `repo/docs` folder it's used by github to provide an endpoint for the repository: [https://igortrinidad.github.io/vue-number-format/](https://igortrinidad.github.io/vue-number-format/), so i use this GH feature to avoid the need of assign a custom domain or third part service for this...
